# Generated by Django 3.1.7 on 2021-04-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whole', '0002_shoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='static/uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Watches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='static/uploads')),
            ],
        ),
    ]
