# Generated by Django 3.1.7 on 2021-04-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whole', '0004_auto_20210413_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
