# Generated by Django 3.1.7 on 2021-04-14 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whole', '0005_auto_20210413_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, null=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(null=True, upload_to='static/uploads')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whole.category')),
            ],
        ),
    ]
